# Generated by Django 4.2.4 on 2023-09-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=100)),
                ('trade_code', models.CharField(max_length=100)),
                ('high', models.FloatField(max_length=100)),
                ('low', models.FloatField(max_length=100)),
                ('open', models.FloatField(max_length=100)),
                ('close', models.FloatField(max_length=100)),
                ('volume', models.FloatField(max_length=100)),
            ],
        ),
    ]
